using System;
using UnityEngine;

namespace UnityEngine
{

public class AndroidJNI
{
    static public IntPtr AllocObject(IntPtr clazz);
    static public int AttachCurrentThread();
    static public bool CallBooleanMethod(IntPtr obj, IntPtr methodID, jvalue[] args);
    static public byte CallByteMethod(IntPtr obj, IntPtr methodID, jvalue[] args);
    static public char CallCharMethod(IntPtr obj, IntPtr methodID, jvalue[] args);
    static public double CallDoubleMethod(IntPtr obj, IntPtr methodID, jvalue[] args);
    static public float CallFloatMethod(IntPtr obj, IntPtr methodID, jvalue[] args);
    static public int CallIntMethod(IntPtr obj, IntPtr methodID, jvalue[] args);
    static public long CallLongMethod(IntPtr obj, IntPtr methodID, jvalue[] args);
    static public IntPtr CallObjectMethod(IntPtr obj, IntPtr methodID, jvalue[] args);
    static public sbyte CallSByteMethod(IntPtr obj, IntPtr methodID, jvalue[] args);
    static public short CallShortMethod(IntPtr obj, IntPtr methodID, jvalue[] args);
    static public bool CallStaticBooleanMethod(IntPtr clazz, IntPtr methodID, jvalue[] args);
    static public byte CallStaticByteMethod(IntPtr clazz, IntPtr methodID, jvalue[] args);
    static public char CallStaticCharMethod(IntPtr clazz, IntPtr methodID, jvalue[] args);
    static public double CallStaticDoubleMethod(IntPtr clazz, IntPtr methodID, jvalue[] args);
    static public float CallStaticFloatMethod(IntPtr clazz, IntPtr methodID, jvalue[] args);
    static public int CallStaticIntMethod(IntPtr clazz, IntPtr methodID, jvalue[] args);
    static public long CallStaticLongMethod(IntPtr clazz, IntPtr methodID, jvalue[] args);
    static public IntPtr CallStaticObjectMethod(IntPtr clazz, IntPtr methodID, jvalue[] args);
    static public sbyte CallStaticSByteMethod(IntPtr clazz, IntPtr methodID, jvalue[] args);
    static public short CallStaticShortMethod(IntPtr clazz, IntPtr methodID, jvalue[] args);
    static public string CallStaticStringMethod(IntPtr clazz, IntPtr methodID, jvalue[] args);
    static public void CallStaticVoidMethod(IntPtr clazz, IntPtr methodID, jvalue[] args);
    static public string CallStringMethod(IntPtr obj, IntPtr methodID, jvalue[] args);
    static public void CallVoidMethod(IntPtr obj, IntPtr methodID, jvalue[] args);
    static public void DeleteGlobalRef(IntPtr obj);
    static public void DeleteLocalRef(IntPtr obj);
    static public int DetachCurrentThread();
    static public int EnsureLocalCapacity(int capacity);
    static public void ExceptionClear();
    static public void ExceptionDescribe();
    static public IntPtr ExceptionOccurred();
    static public void FatalError(string message);
    static public IntPtr FindClass(string name);
    static public bool[] FromBooleanArray(IntPtr array);
    static public byte[] FromByteArray(IntPtr array);
    static public char[] FromCharArray(IntPtr array);
    static public double[] FromDoubleArray(IntPtr array);
    static public float[] FromFloatArray(IntPtr array);
    static public int[] FromIntArray(IntPtr array);
    static public long[] FromLongArray(IntPtr array);
    static public IntPtr[] FromObjectArray(IntPtr array);
    static public IntPtr FromReflectedField(IntPtr refField);
    static public IntPtr FromReflectedMethod(IntPtr refMethod);
    static public sbyte[] FromSByteArray(IntPtr array);
    static public short[] FromShortArray(IntPtr array);
    static public int GetArrayLength(IntPtr array);
    static public bool GetBooleanArrayElement(IntPtr array, int index);
    static public bool GetBooleanField(IntPtr obj, IntPtr fieldID);
    static public byte GetByteArrayElement(IntPtr array, int index);
    static public byte GetByteField(IntPtr obj, IntPtr fieldID);
    static public char GetCharArrayElement(IntPtr array, int index);
    static public char GetCharField(IntPtr obj, IntPtr fieldID);
    static public double GetDoubleArrayElement(IntPtr array, int index);
    static public double GetDoubleField(IntPtr obj, IntPtr fieldID);
    static public IntPtr GetFieldID(IntPtr clazz, string name, string sig);
    static public float GetFloatArrayElement(IntPtr array, int index);
    static public float GetFloatField(IntPtr obj, IntPtr fieldID);
    static public int GetIntArrayElement(IntPtr array, int index);
    static public int GetIntField(IntPtr obj, IntPtr fieldID);
    static public long GetLongArrayElement(IntPtr array, int index);
    static public long GetLongField(IntPtr obj, IntPtr fieldID);
    static public IntPtr GetMethodID(IntPtr clazz, string name, string sig);
    static public IntPtr GetObjectArrayElement(IntPtr array, int index);
    static public IntPtr GetObjectClass(IntPtr obj);
    static public IntPtr GetObjectField(IntPtr obj, IntPtr fieldID);
    static public sbyte GetSByteArrayElement(IntPtr array, int index);
    static public sbyte GetSByteField(IntPtr obj, IntPtr fieldID);
    static public short GetShortArrayElement(IntPtr array, int index);
    static public short GetShortField(IntPtr obj, IntPtr fieldID);
    static public bool GetStaticBooleanField(IntPtr clazz, IntPtr fieldID);
    static public byte GetStaticByteField(IntPtr clazz, IntPtr fieldID);
    static public char GetStaticCharField(IntPtr clazz, IntPtr fieldID);
    static public double GetStaticDoubleField(IntPtr clazz, IntPtr fieldID);
    static public IntPtr GetStaticFieldID(IntPtr clazz, string name, string sig);
    static public float GetStaticFloatField(IntPtr clazz, IntPtr fieldID);
    static public int GetStaticIntField(IntPtr clazz, IntPtr fieldID);
    static public long GetStaticLongField(IntPtr clazz, IntPtr fieldID);
    static public IntPtr GetStaticMethodID(IntPtr clazz, string name, string sig);
    static public IntPtr GetStaticObjectField(IntPtr clazz, IntPtr fieldID);
    static public sbyte GetStaticSByteField(IntPtr clazz, IntPtr fieldID);
    static public short GetStaticShortField(IntPtr clazz, IntPtr fieldID);
    static public string GetStaticStringField(IntPtr clazz, IntPtr fieldID);
    static public string GetStringField(IntPtr obj, IntPtr fieldID);
    static public string GetStringUTFChars(IntPtr str);
    static public int GetStringUTFLength(IntPtr str);
    static public IntPtr GetSuperclass(IntPtr clazz);
    static public int GetVersion();
    static public bool IsAssignableFrom(IntPtr clazz1, IntPtr clazz2);
    static public bool IsInstanceOf(IntPtr obj, IntPtr clazz);
    static public bool IsSameObject(IntPtr obj1, IntPtr obj2);
    static public IntPtr NewBooleanArray(int size);
    static public IntPtr NewByteArray(int size);
    static public IntPtr NewCharArray(int size);
    static public IntPtr NewDoubleArray(int size);
    static public IntPtr NewFloatArray(int size);
    static public IntPtr NewGlobalRef(IntPtr obj);
    static public IntPtr NewIntArray(int size);
    static public IntPtr NewLocalRef(IntPtr obj);
    static public IntPtr NewLongArray(int size);
    static public IntPtr NewObject(IntPtr clazz, IntPtr methodID, jvalue[] args);
    static public IntPtr NewObjectArray(int size, IntPtr clazz, IntPtr obj);
    static public IntPtr NewSByteArray(int size);
    static public IntPtr NewShortArray(int size);
    static public IntPtr NewStringUTF(string bytes);
    static public IntPtr PopLocalFrame(IntPtr ptr);
    static public int PushLocalFrame(int capacity);
    static public void SetBooleanArrayElement(IntPtr array, int index, byte val);
    static public void SetBooleanArrayElement(IntPtr array, int index, bool val);
    static public void SetBooleanField(IntPtr obj, IntPtr fieldID, bool val);
    static public void SetByteArrayElement(IntPtr array, int index, sbyte val);
    static public void SetByteField(IntPtr obj, IntPtr fieldID, byte val);
    static public void SetCharArrayElement(IntPtr array, int index, char val);
    static public void SetCharField(IntPtr obj, IntPtr fieldID, char val);
    static public void SetDoubleArrayElement(IntPtr array, int index, double val);
    static public void SetDoubleField(IntPtr obj, IntPtr fieldID, double val);
    static public void SetFloatArrayElement(IntPtr array, int index, float val);
    static public void SetFloatField(IntPtr obj, IntPtr fieldID, float val);
    static public void SetIntArrayElement(IntPtr array, int index, int val);
    static public void SetIntField(IntPtr obj, IntPtr fieldID, int val);
    static public void SetLongArrayElement(IntPtr array, int index, long val);
    static public void SetLongField(IntPtr obj, IntPtr fieldID, long val);
    static public void SetObjectArrayElement(IntPtr array, int index, IntPtr obj);
    static public void SetObjectField(IntPtr obj, IntPtr fieldID, IntPtr val);
    static public void SetSByteArrayElement(IntPtr array, int index, sbyte val);
    static public void SetSByteField(IntPtr obj, IntPtr fieldID, sbyte val);
    static public void SetShortArrayElement(IntPtr array, int index, short val);
    static public void SetShortField(IntPtr obj, IntPtr fieldID, short val);
    static public void SetStaticBooleanField(IntPtr clazz, IntPtr fieldID, bool val);
    static public void SetStaticByteField(IntPtr clazz, IntPtr fieldID, byte val);
    static public void SetStaticCharField(IntPtr clazz, IntPtr fieldID, char val);
    static public void SetStaticDoubleField(IntPtr clazz, IntPtr fieldID, double val);
    static public void SetStaticFloatField(IntPtr clazz, IntPtr fieldID, float val);
    static public void SetStaticIntField(IntPtr clazz, IntPtr fieldID, int val);
    static public void SetStaticLongField(IntPtr clazz, IntPtr fieldID, long val);
    static public void SetStaticObjectField(IntPtr clazz, IntPtr fieldID, IntPtr val);
    static public void SetStaticSByteField(IntPtr clazz, IntPtr fieldID, sbyte val);
    static public void SetStaticShortField(IntPtr clazz, IntPtr fieldID, short val);
    static public void SetStaticStringField(IntPtr clazz, IntPtr fieldID, string val);
    static public void SetStringField(IntPtr obj, IntPtr fieldID, string val);
    static public int Throw(IntPtr obj);
    static public int ThrowNew(IntPtr clazz, string message);
    static public IntPtr ToBooleanArray(bool[] array);
    static public IntPtr ToByteArray(byte[] array);
    static public IntPtr ToCharArray(char[] array);
    static public IntPtr ToDoubleArray(double[] array);
    static public IntPtr ToFloatArray(float[] array);
    static public IntPtr ToIntArray(int[] array);
    static public IntPtr ToLongArray(long[] array);
    static public IntPtr ToObjectArray(IntPtr[] array, IntPtr arrayClass);
    static public IntPtr ToObjectArray(IntPtr[] array);
    static public IntPtr ToReflectedField(IntPtr clazz, IntPtr fieldID, bool isStatic);
    static public IntPtr ToReflectedMethod(IntPtr clazz, IntPtr methodID, bool isStatic);
    static public IntPtr ToSByteArray(sbyte[] array);
    static public IntPtr ToShortArray(short[] array);

}

}
