using System;
using UnityEngine;

namespace UnityEngine.Rendering
{

public enum BuiltinShaderDefine
{
    UNITY_NO_DXT5nm = 0,
    UNITY_NO_RGBM = 1,
    UNITY_USE_NATIVE_HDR = 2,
    UNITY_ENABLE_REFLECTION_BUFFERS = 3,
    UNITY_FRAMEBUFFER_FETCH_AVAILABLE = 4,
    UNITY_ENABLE_NATIVE_SHADOW_LOOKUPS = 5,
    UNITY_METAL_SHADOWS_USE_POINT_FILTERING = 6,
    UNITY_NO_CUBEMAP_ARRAY = 7,
    UNITY_NO_SCREENSPACE_SHADOWS = 8,
    UNITY_USE_DITHER_MASK_FOR_ALPHABLENDED_SHADOWS = 9,
    UNITY_PBS_USE_BRDF1 = 10,
    UNITY_PBS_USE_BRDF2 = 11,
    UNITY_PBS_USE_BRDF3 = 12,
    UNITY_NO_FULL_STANDARD_SHADER = 13,
    UNITY_SPECCUBE_BOX_PROJECTION = 14,
    UNITY_SPECCUBE_BLENDING = 15,
    UNITY_ENABLE_DETAIL_NORMALMAP = 16,
    SHADER_API_MOBILE = 17,
    SHADER_API_DESKTOP = 18,
    UNITY_HARDWARE_TIER1 = 19,
    UNITY_HARDWARE_TIER2 = 20,
    UNITY_HARDWARE_TIER3 = 21,
    UNITY_COLORSPACE_GAMMA = 22,
    UNITY_LIGHT_PROBE_PROXY_VOLUME = 23,
    UNITY_HALF_PRECISION_FRAGMENT_SHADER_REGISTERS = 24,
    UNITY_LIGHTMAP_DLDR_ENCODING = 25,
    UNITY_LIGHTMAP_RGBM_ENCODING = 26,
    UNITY_LIGHTMAP_FULL_HDR = 27,
}

}
